name: CI

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workspace: [frontend, backend]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint & Prettier (workspace ${{ matrix.workspace }})
        run: |
          if [ "${{ matrix.workspace }}" = "frontend" ]; then
            npx eslint "frontend/**/*.{ts,tsx,js,jsx}"
          else
            npx eslint "backend/**/*.ts"
          fi

      - name: Run tests (workspace ${{ matrix.workspace }})
        run: |
          if [ "${{ matrix.workspace }}" = "frontend" ]; then
            cd frontend && npm test
          else
            cd backend && npm test
          fi
